### ISSUE TITLE
How did you upload the favicon?

### ISSUE THREAD

**Issue by 12944qwerty** [Kenny2github/kenny2github.github.io#3]
How did you upload the favicon? I have to upload it to a image hosting website and then use that raw link.

**Comment by Kenny2github** [comment]
![image](https://user-images.githubusercontent.com/28599280/51581368-ba72eb80-1f02-11e9-89b7-31d8063067fe.png)
Button is only available if you have push access to the repo.

**Comment by 12944qwerty** [comment]
push?

**Comment by Kenny2github** [comment]
I recommend you [learn more about git](https://lmgtfy.com/?q=git+tutorial) before trying to use GitHub, otherwise you're going to remain quite lost...

**Comment by 12944qwerty** [comment]
Oh, but I use chromebook. Is there a way to download the terminal?

**Comment by Kenny2github** [comment]
GitHub really isn't something you can work with on a Chromebook... I recommend you get/use a fully-fledged OS when doing any serious leisure or work. (Basically, don't use any school-issue devices! They will bring you nothing but trouble.)
